# -*- mode: ruby -*-
# vi: set ft=ruby :

#require 'vagrant-vbguest' #Comment since yet incopatible with vagrant 1.1
#require 'vagrant-hostmaster'

Vagrant::Config.run do |config|
  config.vm.box = "sandbox"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui

  config.vm.network :hostonly, "192.168.56.101"
  config.vm.host_name = "sandbox"
  config.vm.customize ["modifyvm", :id, "--memory", 3048] #For dev purpose

  config.vm.provision :puppet, :options => "--verbose --debug" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "sandbox.pp"
  end

  config.vm.customize ["modifyvm", :id, "--rtcuseutc", "on"]
  config.vm.customize ["modifyvm", :id, "--name", "Sandbox HDP Caterpillar", "--groups", "/HortonWorks"]
end
