# -*- mode: ruby -*-
# vi: set ft=ruby :

##########################################################
# to bring machine up do $ vagrant up <machine name>
# 
# Available <Machine name>s:
#  - default: Unsecure Sandbox
#  - secure : Secure Sandbox
#  - test   : Lightweight installation
#             for running unittests [uses local repo]
#  - qa     : full sandbox with preloaded TestData
# 
#  local repo now at http://10.2.2.239:8142
##########################################################

Vagrant.configure("2") do |config|
  config.vm.box = "SandboxBaikalRC1"
  config.vm.box_url = "http://dev2.hortonworks.com.s3.amazonaws.com/sandbox/vagrant/SandboxBaikalRC1.box"

  config.vm.hostname = "sandbox.hortonworks.com"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  
    vb.customize ["modifyvm", :id, "--memory", 4048]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vb.customize ["modifyvm", :id, "--ostype", "Redhat_64"]

    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    vb.customize ["modifyvm", :id, "--nic2", "none"]
    vb.customize ["modifyvm", :id, "--mouse", "usbtablet"]
  end

  ['default', 'qa'].each do |vm|
    config.vm.define vm do |subconf|
      subconf.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--name", "Hortonworks Sandbox 2.0", "--groups", "/Hortonworks"]
      end
    end
  end

  config.vm.define :default do |subconf|
    subconf.vm.provision :puppet, :options => "--verbose --debug" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "sandbox_full.pp"
    end
  end


  config.vm.define :qa do |subconf|
    subconf.vm.provision :puppet, :options => "--verbose --debug" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "sandbox_qa.pp"
    end
  end
  
  config.vm.define :test do |subconf|
    subconf.vm.provision :puppet, :options => "--verbose --debug" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "sandbox_test_machine.pp"
    end

    subconf.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--name", "Sandbox Testbox", "--groups", "/Hortonworks"]
    end
  end


  # config.vm.define :secure do |subconf|
  #   config.vm.box = "sandbox-hdp-2.0.5-secure"
  #   config.vm.box_url = "http://dev2.hortonworks.com.s3.amazonaws.com/stuff/sandbox-hdp-2.0.5-secure.box"


  #   subconf.vm.provision :puppet, :options => "--verbose --debug" do |puppet|
  #     puppet.manifests_path = "manifests"
  #     puppet.manifest_file  = "sandbox_secure.pp"
  #   end

  #   subconf.vm.provider :virtualbox do |vb|
  #     vb.customize ["modifyvm", :id, "--name", "Hortonworks Sandbox 2.0 Secure", "--groups", "/Hortonworks"]
  #   end
  # end


  ['default', 'qa'].each do |vm|
      config.vm.define vm do |subconf|
        subconf.vm.network :forwarded_port, guest: 80, host: 42080, host_ip: "127.0.0.1", auto_correct: true #Apache http
        subconf.vm.network :forwarded_port, guest: 111, host: 42111, host_ip: "127.0.0.1", auto_correct: true #NFS portmap
        subconf.vm.network :forwarded_port, guest: 8000, host: 8000, host_ip: "127.0.0.1", auto_correct: true #Hue
        subconf.vm.network :forwarded_port, guest: 8020, host: 8020, host_ip: "127.0.0.1", auto_correct: true #Hdfs
        subconf.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "127.0.0.1", auto_correct: true #Ambari
        subconf.vm.network :forwarded_port, guest: 8088, host: 8088, host_ip: "127.0.0.1", auto_correct: true #Yarn RM
        subconf.vm.network :forwarded_port, guest: 8443, host: 8443, host_ip: "127.0.0.1", auto_correct: true #Knox gateway
        subconf.vm.network :forwarded_port, guest: 15000, host: 15000, host_ip: "127.0.0.1", auto_correct: true #Falcon
      end
  end

end
