# -*- mode: ruby -*-
# vi: set ft=ruby :

##########################################################
# to bring machine up do $ vagrant up 
# 
##########################################################

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS6.5-basebox"
  config.vm.box_url = "http://dev2.hortonworks.com.s3.amazonaws.com/sandbox/vagrant/CentOS6.5-basebox.box"
  config.vm.box_download_checksum = "8166183c85d4f0564c8341cdd2532eef7c8df9fde397e3fd583ee830af3b90af"
  config.vm.box_download_checksum_type = "sha256"
  config.vm.hostname = "sandbox.hortonworks.com"

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on the "Usage" link above
    config.cache.scope = :box

    config.cache.enable :generic, {
      "wget" => { cache_dir: "/var/cache/wget" },
    }
  end

  config.vm.provider :virtualbox do |vb|
#    vb.gui = true
  
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vb.customize ["modifyvm", :id, "--ostype", "Redhat_64"]

    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    vb.customize ["modifyvm", :id, "--nic2", "none"]
    vb.customize ["modifyvm", :id, "--mouse", "usbtablet"]

    vb.customize ["modifyvm", :id, "--name", "Hortonworks_Sandbox_Bluprints", "--groups", "/Hortonworks"]
  end

  
  config.vm.provision :puppet, :options => "--verbose --debug" do |puppet|
     puppet.hiera_config_path = "hiera.yaml"
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "init.pp"
     puppet.module_path = "modules"
     puppet.facter = {
       "nodes_count" => 1,
       "nodecount" => 1,
       "role" => "ambari",
       "sandbox" => "true",
       "xasecure_version" => "3.5.001"
     }
  end
  

  config.vm.network :forwarded_port, guest: 80, host: 42080, host_ip: "127.0.0.1", auto_correct: true #Apache http
  config.vm.network :forwarded_port, guest: 111, host: 42111, host_ip: "127.0.0.1", auto_correct: true #NFS portmap
  config.vm.network :forwarded_port, guest: 4040, host: 4040, host_ip: "127.0.0.1", auto_correct: true #Spark
  config.vm.network :forwarded_port, guest: 6080, host: 6080, host_ip: "127.0.0.1", auto_correct: true #XASecure Manager
  config.vm.network :forwarded_port, guest: 8000, host: 8000, host_ip: "127.0.0.1", auto_correct: true #Hue
  config.vm.network :forwarded_port, guest: 8020, host: 8020, host_ip: "127.0.0.1", auto_correct: true #Hdfs
  config.vm.network :forwarded_port, guest: 8042, host: 8042, host_ip: "127.0.0.1", auto_correct: true #NodeManager
  config.vm.network :forwarded_port, guest: 8050, host: 8050, host_ip: "127.0.0.1", auto_correct: true #Resource manager
  config.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "127.0.0.1", auto_correct: true #Ambari
  config.vm.network :forwarded_port, guest: 8088, host: 8088, host_ip: "127.0.0.1", auto_correct: true #Yarn RM
  config.vm.network :forwarded_port, guest: 8443, host: 8443, host_ip: "127.0.0.1", auto_correct: true #Knox gateway
  config.vm.network :forwarded_port, guest: 8744, host: 8744, host_ip: "127.0.0.1", auto_correct: true #Storm UI
  config.vm.network :forwarded_port, guest: 8888, host: 8888, host_ip: "127.0.0.1", auto_correct: true #Tutorials
  config.vm.network :forwarded_port, guest: 8983, host: 8983, host_ip: "127.0.0.1", auto_correct: true #Solr
  config.vm.network :forwarded_port, guest: 10000, host: 10000, host_ip: "127.0.0.1", auto_correct: true #HiveServer2 thrift
  config.vm.network :forwarded_port, guest: 10001, host: 10001, host_ip: "127.0.0.1", auto_correct: true #HiveServer2 thrift http
  config.vm.network :forwarded_port, guest: 11000, host: 11000, host_ip: "127.0.0.1", auto_correct: true #Oozie
  config.vm.network :forwarded_port, guest: 15000, host: 15000, host_ip: "127.0.0.1", auto_correct: true #Falcon
  config.vm.network :forwarded_port, guest: 19888, host: 19888, host_ip: "127.0.0.1", auto_correct: true #Job history
  config.vm.network :forwarded_port, guest: 50070, host: 50070, host_ip: "127.0.0.1", auto_correct: true #WebHdfs
  config.vm.network :forwarded_port, guest: 50075, host: 50075, host_ip: "127.0.0.1", auto_correct: true #Datanode
  config.vm.network :forwarded_port, guest: 50111, host: 50111, host_ip: "127.0.0.1", auto_correct: true #WebHcat
  config.vm.network :forwarded_port, guest: 60010, host: 60010, host_ip: "127.0.0.1", auto_correct: true #HBase Master
  config.vm.network :forwarded_port, guest: 60030, host: 60030, host_ip: "127.0.0.1", auto_correct: true #HBase Region
  config.vm.network :forwarded_port, guest: 60080, host: 60080, host_ip: "127.0.0.1", auto_correct: true #WebHBase
end
