#!/bin/bash
# ambari init script
# chkconfig: 345 99 1
# description: startup script

SCRIPTS_PATH=/usr/lib/start_scripts
NAME="ambari"
LOG="/var/log/$NAME_script.log"

source /etc/rc.d/init.d/functions

source $SCRIPTS_PATH/consts.sh

start() {
    printf "%-50s\n" "Starting Ambari..." | tee -a $LOG
    
    make --makefile $SCRIPTS_PATH/start_deps.mf -B Ambari -j -i
    echo "===========================";
    echo;
    echo "To disable auto-start of Ambari do";
    echo "  # chkconfig ambari off";
    echo;
    echo "===========================";
}


stop() {
	echo "Stopping Ganglia"
	/etc/init.d/hdp-gmetad stop
	/etc/init.d/hdp-gmond stop

	echo "Stopping Nagios"
	/etc/init.d/nagios stop

	echo "Stopping Ambari server"
	ambari-server stop

	echo "Stopping Ambari agent"
	ambari-agent stop
}

case "$1" in
start)
	chkconfig ambari on
	start
	;;
stop)
	chkconfig ambari off
	stop
	;;

restart)
    stop
    start
	;;

*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac