#!/bin/bash
# startup script
# chkconfig: 5 98 1
# description: startup script

SCRIPTS_PATH="/usr/lib/start_scripts"
NAME="startup_script"
LOG="/var/log/startup_script.log"

source /etc/rc.d/init.d/functions

source $SCRIPTS_PATH/consts.sh

function restart() {
    date >> $LOG
    [ "$1" == "-r" ] && str="Stopping HDP..." || str="Starting HDP..."
    printf "%-70s\n" "$str" | tee -a $LOG
    bash $SCRIPTS_PATH/stop.sh >> $LOG 2>&1

    [ "$1" == "-r" ] && printf "%-70s\n" "Starting HDP..." | tee -a $LOG
    bash $SCRIPTS_PATH/start.sh >> $LOG 2>&1
}


case "$1" in
start)
    printf "%-50s\n" "Starting $NAME..." | tee -a $LOG
    

    /etc/init.d/mysqld start >> $LOG  #To make run.sh work (tutorials update)

    #bash $SCRIPTS_PATH/sandbox_component_versions.sh

    printf "%-50s\n" "Updating IP..." | tee -a $LOG
    bash $SCRIPTS_PATH/gen_hosts.sh
   
    printf "%-50s\n" "Updating sandbox..." | tee -a $LOG
    cd /usr/lib/sandbox-shared

    sed -i 1i"nameserver 8.8.8.8" /etc/resolv.conf

    sudo -u sandbox git fetch >> /var/log/startup_script.log 2>&1
    sudo -u sandbox git checkout $BRANCH >> /var/log/startup_script.log 2>&1
    sudo -u sandbox git stash  >> /var/log/startup_script.log 2>&1
    pull_res=$(sudo -u sandbox git pull origin $BRANCH 2>> $LOG)
    echo $pull_res >> $LOG

    chown sandbox:sandbox -R /usr/lib/sandbox-shared
    [ ! "$pull_res" = "Already up-to-date." ] && /usr/lib/hue/build/env/bin/hue migrate  >> $LOG 2>&1
    sudo -u sandbox bash /usr/lib/tutorials/tutorials_app/run/run.sh >> $LOG 2>&1

    echo "Starting HDP ..."
    bash $SCRIPTS_PATH/start.sh
    sudo -u hdfs hadoop dfsadmin -safemode leave
    
    printf "%-50s\n" "Starting sandbox..." | tee -a $LOG
    cd /usr/lib/hue
    /etc/init.d/supervisord start >> $LOG 2>&1
    
    #open -c 1 -f -- python /usr/lib/start_scripts/splash.py
;;
stop)
    date >> $LOG
    bash $SCRIPTS_PATH/stop.sh >> $LOG 2>&1
    /etc/init.d/supervisord stop >> $LOG 2>&1
;;

restart)
    restart -r
;;

*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
