#!/bin/bash
# startup script
# chkconfig: 5 99 1
# description: startup script

SCRIPTS_PATH="/home/sandbox/start_scripts"
NAME="startup_script"
LOG="/var/log/startup_script.log"

source /etc/rc.d/init.d/functions

function restart() {
    date >> $LOG
    [ "$1" == "-r" ] && str="Stopping HDP..." || str="Starting HDP..."
    printf "%-70s\n" "$str" | tee -a $LOG
    bash $SCRIPTS_PATH/stop.sh >> $LOG 2>&1

    [ "$1" == "-r" ] && printf "%-70s\n" "Starting HDP..." | tee -a $LOG
    bash $SCRIPTS_PATH/start.sh >> $LOG 2>&1
}


case "$1" in
start)
    printf "%-50s\n" "Starting $NAME..." | tee -a $LOG
    
    dhclient &

    /etc/init.d/mysqld start >> $LOG  #To make run.sh work (tutorials update)

    bash $SCRIPTS_PATH/sandbox_component_versions.sh

    printf "%-50s\n" "Updating IP..." | tee -a $LOG
    bash $SCRIPTS_PATH/gen_hosts.sh
   
    printf "%-50s\n" "Updating sandbox..." | tee -a $LOG
    cd /home/sandbox/sandbox-shared

    sudo -u sandbox git fetch >> /var/log/startup_script.log 2>&1
    sudo -u sandbox git checkout Alstom >> /var/log/startup_script.log 2>&1
    sudo -u sandbox git pull origin Alstom >> /var/log/startup_script.log 2>&1
    chown sandbox:sandbox -R /home/sandbox/sandbox-shared
    /home/sandbox/hue/build/env/bin/hue migrate  >> $LOG 2>&1
    sudo -u sandbox bash /home/sandbox/tutorials/tutorials_app/run/run.sh >> $LOG 2>&1
    cd - >> $LOG 2>&1
    [ "z$2" == "z--fake" ] || restart -s
    sudo -u hdfs hadoop dfsadmin -safemode leave
    
    printf "%-50s\n" "Starting sandbox..." | tee -a $LOG
    /etc/init.d/supervisord start >> $LOG 2>&1
    
    echo "Hortonworks Data Platform Sandbox 1.0.4" > /etc/issue

    echo "You can now launch sandbox on http://$(getent ahosts `hostname` | awk '{print $1}' | head -n 1):8888/" | tee -a /etc/issue
    
    echo >> /etc/issue
;;
stop)
    date >> $LOG
    bash $SCRIPTS_PATH/stop.sh >> $LOG 2>&1
    /etc/init.d/supervisord stop >> $LOG 2>&1
;;

restart)
    restart -r
;;

*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
