# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

[[ $(tty) = "/dev/tty1" ]] && bash /usr/lib/hue/tools/start_scripts/post_start.sh
